[package]
name = "rust-passmaker"
version = "0.1.0"
authors = ["Trevor Opiyo <46691585+Trevor-Opiyo@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
