[dependencies]
io = "0.0.2"
rand = "0.8.4"

[package]
authors = ["Trevor Opiyo <46691585+Trevor-Opiyo@users.noreply.github.com>"]
description = "A password generator CLI written in Rust."
edition = "2018"
license = "GPL"
name = "rust-passmaker"
next_edition = 2021
version = "0.2.3"
